<?php

namespace AppBundle\Repository;

use AppBundle\Entity\FeaturedImage;

/**
 * FeaturedImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedImageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return FeaturedImage[]
     */
    public function findCarouseImages()
    {
        return $this->createQueryBuilder('f')
            ->where('f.active = :active')
            ->setParameter('active', true)
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();
    }
}
