# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
# parameters:
#    parameter_name: value

services:
    sonata.admin.product:
        class: AppBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Product" }
        arguments: [~, AppBundle\Entity\Product, ~]

    sonata.admin.featured_image:
        class: AppBundle\Admin\FeaturedImageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Featured Image" }
        arguments: [~, AppBundle\Entity\FeaturedImage, ~]

    appmailer:
        class: AppBundle\Service\AppMailer
        arguments: ["@mailer"]
