assetic:
    debug: '%kernel.debug%'
    use_controller: false
    bundles: []
    #node: /usr/bin/nodejs
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: "%kernel.root_dir%/../node_modules/uglify-js/bin/uglifyjs"
